### ISSUE TITLE
Create release for v1.3.1

### ISSUE THREAD

**Issue by Reidsy** [eduncan911/podcast#11]
With go modules being announced https://blog.golang.org/modules2019 `go get` will now download v1.3.0 because it is the most recent tag.

Can the lastest master be tagged with `v1.3.1`?

**Comment by eduncan911** [comment]
Ah hah. I missed that announcement.

Will do!  I am currently out if the country for work without my personal laptop.  So I'll have to wait until around Xmas when I am back.

**Comment by Reidsy** [comment]
Thanks @eduncan911 

Enjoy your xmas.

**Comment by Reidsy** [comment]
As a workaround to this issue, the following can be added to `go.mod` to get the latest commit
```
require (
    github.com/eduncan911/podcast v0.0.0-20171210162110-10213c61cee5
)
```

**Comment by eduncan911** [comment]
Ah yes, getting to this soon! Was playing with GitHub actions for a new CI pipeline which would auto-tag.

Thanks for the poke

**Comment by eduncan911** [comment]
Going to close this for now.  About to make another release soon with all the changes once I verify the new code, tests, and github actions pipeline - to do it all for me going forward.

Going to also delete the `develop` branch as  some don't follow it.
